server:
  port: 8081

spring:
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: coffee
      profile: status

  datasource:
    url: jdbc:mysql://localhost:3306/msa_status?createDatabaseIfNotExist=TRUE&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: wodyd78910**
    driver-class-name: com.mysql.cj.jdbc.Driver