server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
#        encrypt.enabled: true
        git:
          uri: https://github.com/J-Yong99/eum-msa-config
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true